<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
        <?php if ($block->getTitle()) : ?>
            <div style="margin-bottom: 10px">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <?php 
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $items = $block->getProductCollection()->getItems();
            $image = 'new_products_content_widget_grid'; 
            $type = 'widget-product-grid';
            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
        ?>
        <div class="owl-carousel owl-theme">
        <?php foreach ($items as $_item) : ?>
                <div class="item">
                    <div style="margin-left: 10px">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>
                        <strong class="product-item-name">
                            <a  title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                class="product-item-link">
                                <?= $block->escapeHtml($_item->getName()) ?>
                            </a>
                        </strong>
                            <?php if ($templateType) : ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?= $block->getProductPriceHtml($_item, $type) ?>

                            <?= $block->getProductDetailsHtml($_item) ?>
                            <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                <div class="product-item">
                                <div class="product-item-actions">
                                <?php if ($showCart) : ?>
                                    <?php if ($_item->isSaleable()) : ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                    <?php else : ?>
                                        <?php if ($_item->getIsSalable()) : ?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else : ?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($showWishlist || $showCompare) : ?>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php //phpcs:disable ?>
                                        <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                        <?php //phpcs:enable ?>
                                            <a href="#"
                                                data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                            </a>
                                        <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                <?php //phpcs:disable ?>
                                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                <?php //phpcs:enable ?>
                                                <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                </div>
                                </div>
                            <?php endif; ?>
                    </div>
                </div>
        <?php endforeach ?>
        </div>
<?php endif;?>
</div>
    <script type="text/javascript">
        require(['jquery', 'owlcarousel'], function($) {
            $('.owl-theme').owlCarousel({
                rtl:false,
                loop:true,
                margin:10,
                nav:true,
                responsive:{
                    0:{
                        items:1
                    },
                    600:{
                        items:3
                    },
                    1000:{
                        items:5
                    }
                }
            })
        });
    </script>

